name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file ./client/Dockerfile.dev --tag rasimthegrey/react-test ./client
    - name: Test the Image
      run: docker run -e CI=true rasimthegrey/react-test npm test
    - name: Build Client
      run: docker build -t rasimthegrey/multi-client ./client
    - name: Build NGINX
      run: docker build -t rasimthegrey/multi-nginx ./nginx
    - name: Build Server
      run: docker build -t rasimthegrey/multi-server ./server
    - name: Build Worker
      run: docker build -t rasimthegrey/multi-worker ./worker
    - name: Log in to docker Hub
      run: echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_ID" --password-stdin
    - name: push images to docker hub
      run: docker push rasimthegrey/multi-client
    - name: push images to docker hub
      run: docker push rasimthegrey/multi-nginx
    - name: push images to docker hub
      run: docker push rasimthegrey/multi-server
    - name: push images to docker hub
      run: docker push rasimthegrey/multi-worker
      