name: Build and Push to Amazon ECR

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push the Image to Amazon ECR
        id: build-images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fibonacci-calculator
        run: |
          docker build -t multi-client ./client 
          docker tag multi-client:latest $ECR_REGISTRY/$ECR_REPOSITORY:multi-client
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:multi-client

          docker build -t multi-nginx ./nginx 
          docker tag multi-nginx:latest $ECR_REGISTRY/$ECR_REPOSITORY:multi-nginx
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:multi-nginx

          docker build -t multi-server ./server 
          docker tag multi-server:latest $ECR_REGISTRY/$ECR_REPOSITORY:multi-server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:multi-server

          docker build -t multi-worker ./worker 
          docker tag multi-worker:latest $ECR_REGISTRY/$ECR_REPOSITORY:multi-worker
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:multi-worker